apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: {{ .Release.Namespace }}
data:
  config.yaml.erb: |
    route:
      match:
        - receiver: "dump"
    receivers:
      - name: "dump"
        elasticsearch:
          hosts:
          - https://{{ .Release.Name }}-es-http:9200
          index: kube-events
          username: elastic
          password: <%= ENV['ES_PASSWORD'] %>
          tls:
            insecureSkipVerify: true
            # caFile: 
